# Generated by Django 4.2 on 2023-12-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airplane_id", models.IntegerField(unique=True)),
                ("passenger_count", models.IntegerField()),
            ],
            options={
                "verbose_name": "Airplane",
                "verbose_name_plural": "Airplanes",
            },
        ),
    ]
